name: Generate Changelog
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    # Avoid overwriting the changelog on release PRs
    if: github.head_ref != 'chore/release' && github.event.pull_request.draft == false
    # Only run if the PR is not a draft and is targeting the master branch
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository
          uses: actions/checkout@v5
          with:
            ref: ${{ github.head_ref }}
            fetch-depth: 0
        - uses: orhun/git-cliff-action@v4
          id: git-cliff
          with:
            config: cliff.toml
            args: --verbose
          env:
            OUTPUT: CHANGELOG.md
            GITHUB_REPO: ${{ github.repository }}
        - uses: stefanzweifel/git-auto-commit-action@v7
          with:
            commit_message: 'chore(changelog): update CHANGELOG.md'
            branch: ${{ github.head_ref }}
            file_pattern: CHANGELOG.md
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}