name: Generate Changelog
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: orhun/git-cliff-action@v4
          id: git-cliff
          with:
            config: cliff.toml
            args: --verbose
          env:
            OUTPUT: CHANGELOG.md
            GITHUB_REPO: ${{ github.repository }}
        - uses: peter-evans/create-pull-request@v7
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            title: "chore(changelog): Update CHANGELOG.md"
            branch: "docs/changelog"
            add-paths: "CHANGELOG.md"
            body: "This PR was automatically created by the Generate Changelog action."
            commit-message: "chore(changelog): Update CHANGELOG.md"
            labels: "documentation"
