name: Release Preparation
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-release:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - uses: orhun/git-cliff-action@f50e11560dce63f7c33227798f90b924471a88b5 # v4.8.0
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose --bump
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
      - uses: taiki-e/install-action@25435dc8dd3baed7417e0c96d3fe89013a5b2e09 # v2.81.3
        with:
          tool: cargo-edit
      - name: Update Cargo version
        shell: bash
        env:
          RAW_VERSION: ${{ steps.git-cliff.outputs.version }}
        run: |
          VERSION="${RAW_VERSION#v}"
          echo "Cargo version: ${VERSION}"
          cargo set-version "${VERSION}"
      - run: cargo check
      # Only create PR on push events
      - if: github.event_name == 'push'
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(release): prepare for ${{ steps.git-cliff.outputs.version }}"
          branch: "chore/release"
          add-paths: "CHANGELOG.md, Cargo.toml, Cargo.lock"
          body: "This PR was automatically created by the Release Preparation action."
          commit-message: "chore(release): prepare for ${{ steps.git-cliff.outputs.version }}"
