name: Review on Pull Request
permissions:
  contents: read
on:
  pull_request:

jobs:
  rust:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - run: rustup toolchain install stable --profile minimal --no-self-update
      - uses: taiki-e/install-action@v2
        with:
          tool: clippy-sarif, sarif-fmt
      - run: cargo clippy --message-format=json | clippy-sarif | sarif-fmt